version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_api
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8082
      - DB_HOST=ambev.developerevaluation.database
      - DB_PORT=5432
      - DB_NAME=developer_evaluation
      - DB_USER=developer
      - DB_PASS=ev@luAt10n
      - RABBITMQ_HOSTNAME=ambev.developerevaluation.rabbitmq
      - RABBITMQ_USERNAME=developer
      - RABBITMQ_PASSWORD=ev@luAt10n
      - ConnectionStrings__DefaultConnection=Host=ambev.developerevaluation.database;Port=5432;Database=developer_evaluation;Username=developer;Password=ev@luAt10n;Pooling=true;
      - ConnectionStrings__MongoDB=mongodb://ambev.developerevaluation.nosql:27017/developer_evaluation
    ports:
      - "8080:8080"
      - "8082:8082"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - ambev_network
    depends_on:
      ambev.developerevaluation.database:
        condition: service_healthy

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ambev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d developer_evaluation"]
      interval: 5s
      retries: 5
      timeout: 3s

  ambev.developerevaluation.nosql:
    container_name: ambev_developer_evaluation_nosql
    image: mongo:8.0
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: developer
    #  MONGO_INITDB_ROOT_PASSWORD: evaluAt10n
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ambev_network

  ambev.developerevaluation.cache:
    container_name: ambev_developer_evaluation_cache
    image: redis:7.4.1-alpine
    command: redis-server --requirepass ev@luAt10n
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ambev_network
  
  ambev.developerevaluation.rabbitmq:
    container_name: ambev_developer_evaluation_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: ev@luAt10n
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ambev_network

networks:
  ambev_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:  